# Generated by Django 4.0.4 on 2022-05-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovie', '0003_alter_movie_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.TextField(),
        ),
    ]
