# Generated by Django 4.0.4 on 2022-05-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovie', '0005_userinfo_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'ACTION'), ('comedy', 'COMEDY'), ('drama', 'DRAMA'), ('science fiction', 'SCIENCE FICTION'), ('animation', 'ANIMATION'), ('horror', 'HORROR'), ('romance', 'ROMANCE'), ('crime', 'CRIME'), ('thriller', 'THRILLER'), ('sports', 'SPORTS')], default='drama', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(choices=[('pg', 'PG'), ('pg-13', 'PG-13'), ('g', 'G'), ('r', 'R'), ('nc-17', 'NC-17')], default='pg', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writers',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
