# Generated by Django 4.0.4 on 2022-05-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovie', '0006_alter_movie_actors_alter_movie_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(choices=[('pg', 'PG'), ('pg-13', 'PG-13'), ('g', 'G'), ('r', 'R'), ('nc-17', 'NC-17')], default='pg', max_length=7, null=True),
        ),
    ]
