# Generated by Django 4.0.4 on 2022-05-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovie', '0008_alter_movie_actors_alter_movie_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'ACTION'), ('Comedy', 'COMEDY'), ('Drama', 'DRAMA'), ('Science Fiction', 'SCIENCE FICTION'), ('Animation', 'ANIMATION'), ('Horror', 'HORROR'), ('Romance', 'ROMANCE'), ('Crime', 'CRIME'), ('Thriller', 'THRILLER'), ('Sports', 'SPORTS')], default='drama', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(choices=[('PG', 'PG'), ('PG-13', 'PG-13'), ('G', 'G'), ('R', 'R'), ('NC-17', 'NC-17')], default='pg', max_length=7, null=True),
        ),
    ]
