# Generated by Django 4.0.4 on 2022-05-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovie', '0009_alter_movie_genre_alter_movie_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Science Fiction', 'Science Fiction'), ('Animation', 'Animation'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Crime', 'Crime'), ('Thriller', 'Thriller'), ('Sports', 'Sports')], default='Drama', max_length=500, null=True),
        ),
    ]
