# Generated by Django 4.0.4 on 2022-05-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovie', '0011_alter_movie_actors_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
