# Generated by Django 4.0.4 on 2022-05-17 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ViewMovie', '0012_alter_movie_directors_alter_movie_writers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_reviewed',
            new_name='movie',
        ),
        migrations.AddField(
            model_name='review',
            name='full_review',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_summary',
            field=models.TextField(max_length=50),
        ),
    ]
