# Generated by Django 4.0.4 on 2022-05-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovie', '0013_rename_movie_reviewed_review_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
