# Generated by Django 4.0.4 on 2022-05-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovie', '0015_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
