# Generated by Django 4.0.4 on 2022-05-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovie', '0021_alter_movie_collection_alter_movie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.DateTimeField(
                auto_now_add=True, default='2022-05-20 08:12:12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='time',
            field=models.DateTimeField(
                auto_now_add=True, default='2022-05-20 08:12:12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.DateTimeField(
                auto_now_add=True, default='2022-05-20 08:12:12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='time',
            field=models.DateTimeField(
                auto_now_add=True, default='2022-05-20 08:12:12'),
            preserve_default=False,
        ),
    ]
