# Generated by Django 4.0.4 on 2022-05-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovie', '0022_movie_time_notifications_time_review_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='collection',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
