# Generated by Django 4.0.4 on 2022-05-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovie', '0023_alter_movie_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
