# Generated by Django 4.0.4 on 2022-05-26 18:18

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovie', '0027_alter_movie_time_alter_review_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Science Fiction', 'Science Fiction'), ('Animation', 'Animation'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Crime', 'Crime'), ('Thriller', 'Thriller'), ('Sports', 'Sports')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(choices=[('PG', 'PG'), ('PG-13', 'PG-13'), ('G', 'G'), ('R', 'R'), ('NC-17', 'NC-17')], default='PG', max_length=7),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_summary',
            field=models.TextField(max_length=20),
        ),
    ]
